### ISSUE TITLE
data: iOS-Development roadmap

### ISSUE THREAD

**Issue by siddhigate** [WeMakeDevs/roadmap-runner#56]
### What would you like to share?

- Create a JSON file of [iOS-Development Roadmap](https://github.com/WeMakeDevs/roadmaps/tree/main/iOS-Development#readme) like [this format](https://github.com/siddhigate/roadmap-runner/tree/main/client/src/data)
- Save the JSON file in [this folder](https://github.com/siddhigate/roadmap-runner/tree/main/server/seed/data)

### Additional information

Note: The added roadmap will not be reflected in the UI

**Comment by kedaroo** [comment]
Hey @OMGATE23 , assigning this issue to you!
All the best!

**Comment by OMGATE23** [comment]
@siddhigate @kedaroo  what image should I use for the banner image?

**Comment by siddhigate** [comment]
> @siddhigate @kedaroo what image should I use for the banner image?

You can this: https://res.cloudinary.com/dqkl3iifo/image/upload/v1680107600/roadmaps/ios-development_xworzl.jpg
