### ISSUE TITLE
data: Blockchain roadmap

### ISSUE THREAD

**Issue by siddhigate** [WeMakeDevs/roadmap-runner#57]
### What would you like to share?

- Create a JSON file of [Blockchain Roadmap](https://github.com/WeMakeDevs/roadmaps/tree/main/Blockchain#readme) like [this format](https://github.com/WeMakeDevs/roadmap-runner/blob/main/server/seed/data/android.json)
- Save the JSON file in [this folder server/seed/data/](https://github.com/siddhigate/roadmap-runner/tree/main/server/seed/data)

### Additional information

Note: The added roadmap will not be reflected in the UI

**Comment by harshithasudhakar** [comment]
I would like to work on this. Please assign me.

**Comment by siddhigate** [comment]
@harshithasudhakar assigned. Good luck!

**Comment by harshithasudhakar** [comment]
> @harshithasudhakar assigned. Good luck!

Thanks! I would like to have more clarity on "[this format](https://github.com/siddhigate/roadmap-runner/tree/main/client/src/data)" in the [above description](https://github.com/WeMakeDevs/roadmap-runner/issues/57#issue-1641002338). The webpage it is supposed to redirect me to, doesn't seem to be available.

**Comment by siddhigate** [comment]
> > @harshithasudhakar assigned. Good luck!
> 
> Thanks! I would like to have more clarity on "[this format](https://github.com/siddhigate/roadmap-runner/tree/main/client/src/data)" in the [above description](https://github.com/WeMakeDevs/roadmap-runner/issues/57#issue-1641002338). The webpage it is supposed to redirect me to, doesn't seem to be available.

Have updated the issue description.

**Comment by harshithasudhakar** [comment]
> Hey @harshithasudhakar , are u still working on this issue??

I've finished, and made the PR as well. It is yet to be reviewed and merged.

**Comment by praveenzsp** [comment]
Ok, Thank you

**Comment by harshithasudhakar** [comment]
@siddhigate I have made the JSON file for the roadmap and submitted a PR for it. Please do review it.
