### ISSUE TITLE
[docs]Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [WeMakeDevs/roadmap-runner#66]
### Category of documentation update

I would like to make some changes to structuring of add some features to make the README.md more appealing

I would like to be assigned to the issue if approved

### Describe the change you think might work

+ Better paragraph structure
+ Better formatting
+ Visual badges
+ emojis
+ etc

**Comment by siddhigate** [comment]
Assigning this to you @the-amazing-atharva

**Comment by the-amazing-atharva** [comment]
Working on it soon!
