### ISSUE TITLE
[docs] Adding Tech Stack badges

### ISSUE THREAD

**Issue by the-amazing-atharva** [WeMakeDevs/roadmap-runner#69]
### Category of documentation update

+ Adding a heading called Tech Stack
+ Adding visually appealing badges for the same
+ Additional support to work mentioned in #66 and #68 

**Can the author(s) list the tech stack for the project so that I can add the required badges**

Also, do assign if approved!

### Describe the change you think might work

-

**Comment by kedaroo** [comment]
Hey @the-amazing-atharva , assigning the issue to you. All the best!

**Comment by kedaroo** [comment]
### Tech Stack

- React.js
- Node.js
- Express.js
- MongoDB (with Mongoose as ODM)
- Firebase (For Auth)

 @the-amazing-atharva , hope this help 🙌

**Comment by the-amazing-atharva** [comment]
> ### Tech Stack
> * React.js
> * Node.js
> * Express.js
> * MongoDB (with Mongoose as ODM)
> * Firebase (For Auth)
> * Render (For hosting backend)
> * Vercel (For hosting client website)
> 
> @the-amazing-atharva , hope this help 🙌

Working on it soon!!!

**Comment by the-amazing-atharva** [comment]
Thoughts @kedaroo ?
I can change the structure by classifying them in sections or if this looks cool, I can leave it as it is
![image](https://user-images.githubusercontent.com/121221252/229035933-9e0e12b8-2fa2-42ad-a51b-18a68f828e2d.png)

**Comment by the-amazing-atharva** [comment]
> Look good @the-amazing-atharva !

Thanks, sending a PR

**Comment by AnuragThePathak** [comment]
@the-amazing-atharva from the next time, use separate branches for separate PR.

**Comment by the-amazing-atharva** [comment]
> @the-amazing-atharva from the next time, use separate branches for separate PR.

I have used separate branches only bro but i am actually new to the GitHub workflow so did not want any conflicts
