### ISSUE TITLE
[feat][add link to the logo]

### ISSUE THREAD

**Issue by Nakamcode** [WeMakeDevs/roadmap-runner#77]
### Would you like to have a new feature? Please describe.

add a hyperlink to the logo, to send the user to the home page;

### How would this feature be beneficial for the project

- Yes, it will improve the SEO of the website.

- A user often clicked on a site logo to get to your site, so it is consistent and makes perfect sense for any click on the same logo to take you back to that same entry point.

**Comment by gulshanpr** [comment]
can i work on it?

**Comment by ydv-ankit** [comment]
I'm working on it.

**Comment by Nakamcode** [comment]
Good to hear
